name: Deploy to App Engine and Notify Slack

on:
  push:
    branches:
      - master

  workflow_dispatch:  # ✅ Enables manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate with Service Account  # ✅ Fix for "no active account" error
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > "${HOME}/gcp-key.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"

      - name: Deploy to App Engine
        run: |
          gcloud app deploy --quiet
        working-directory: ./app  # ✅ points to the correct folder

      - name: Publish Pub/Sub Message
        run: |
          gcloud pubsub topics publish app-deploy-topic \
            --message="✅ App Engine deployed successfully via GitHub Actions!"

      - name: Deploy Cloud Function (notify_slack)
        run: |
          gcloud functions deploy notify_slack \
            --runtime python310 \
            --trigger-topic app-deploy-topic \
            --entry-point notify_slack \
            --region us-central1 \
            --gen2 \
            --set-env-vars SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }} \
            --quiet
        working-directory: ./cloud-function
