name: Deploy to App Engine and Notify Slack

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Decode and authenticate service account key
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > "${HOME}/gcp-key.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Ensure Required APIs Are Enabled
        run: |
          REQUIRED_APIS=(
            appengine.googleapis.com
            cloudbuild.googleapis.com
            cloudfunctions.googleapis.com
            pubsub.googleapis.com
            run.googleapis.com
            cloudresourcemanager.googleapis.com
            iam.googleapis.com
          )

          for api in "${REQUIRED_APIS[@]}"; do
            echo "🔍 Checking API: $api"
            if gcloud services list --enabled --format="value(config.name)" | grep -q "$api"; then
              echo "✅ $api is already enabled."
            else
              echo "⏳ Enabling $api..."
              gcloud services enable "$api"
            fi
          done

      - name: Deploy to App Engine
        run: gcloud app deploy --quiet
        working-directory: ./app

      - name: Publish Pub/Sub Message
        run: |
          gcloud pubsub topics publish app-deploy-topic \
            --message="✅ App Engine deployed successfully via GitHub Actions!"

      - name: Deploy Cloud Function (notify_slack)
        run: |
          gcloud functions deploy notify_slack \
            --runtime python310 \
            --trigger-topic app-deploy-topic \
            --entry-point notify_slack \
            --region us-central1 \
            --gen2 \
            --set-env-vars SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }} \
            --quiet
        working-directory: ./cloud-function
