name: Deploy to App Engine and Notify Slack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to App Engine
        run: |
          cd app
          gcloud app deploy --quiet

      - name: Publish Pub/Sub Message
        run: |
          gcloud pubsub topics publish app-deploy-topic \
            --message="App Engine deployed successfully!"
